create table if not exists public.journal_trades (
    id bigint generated by default as identity primary key,
    trade_number integer,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    trade_mode text not null check (trade_mode in ('real', 'simulated')),
    system_name text not null,
    journal_name text not null default 'Apollo Main',
    system_version text,
    candidate_profile text,
    status text not null check (status in ('open', 'closed', 'expired', 'cancelled')),
    trade_date date,
    entry_datetime timestamptz,
    expiration_date date,
    underlying_symbol text,
    spx_at_entry double precision,
    vix_at_entry double precision,
    structure_grade text,
    macro_grade text,
    expected_move double precision,
    expected_move_used double precision,
    expected_move_raw_estimate double precision,
    expected_move_calibrated double precision,
    expected_move_confidence text,
    option_type text,
    short_strike double precision,
    long_strike double precision,
    spread_width double precision,
    contracts integer,
    candidate_credit_estimate double precision,
    actual_entry_credit double precision,
    net_credit_per_contract double precision,
    distance_to_short double precision,
    distance_source text,
    expected_move_source text,
    em_multiple_floor double precision,
    percent_floor double precision,
    boundary_rule_used text,
    actual_distance_to_short double precision,
    actual_em_multiple double precision,
    pass_type text,
    premium_per_contract double precision,
    total_premium double precision,
    max_theoretical_risk double precision,
    total_max_loss double precision,
    risk_efficiency double precision,
    target_em double precision,
    last_status text,
    last_action_sent text,
    last_alert_timestamp timestamptz,
    fallback_used text,
    fallback_rule_name text,
    short_delta double precision,
    notes_entry text,
    exit_datetime timestamptz,
    spx_at_exit double precision,
    actual_exit_value double precision,
    close_method text,
    close_reason text,
    notes_exit text,
    gross_pnl double precision,
    max_risk double precision,
    roi_on_risk double precision,
    hours_held double precision,
    win_loss_result text,
    system text,
    spx_entry double precision,
    vix_entry double precision,
    structure text,
    credit_received double precision,
    max_loss double precision,
    result text,
    pnl double precision,
    max_drawdown double precision,
    exit_type text,
    macro_flag text
);

create index if not exists idx_journal_trades_trade_mode on public.journal_trades (trade_mode);
create index if not exists idx_journal_trades_trade_number on public.journal_trades (trade_number);
create index if not exists idx_journal_trades_created_at on public.journal_trades (created_at desc);

create table if not exists public.journal_trade_close_events (
    id bigint generated by default as identity primary key,
    trade_id bigint not null references public.journal_trades(id) on delete cascade,
    created_at timestamptz not null,
    event_type text not null check (event_type in ('reduce', 'close', 'expire')),
    event_datetime timestamptz,
    contracts_closed integer not null,
    actual_exit_value double precision,
    spx_at_exit double precision,
    close_method text,
    close_reason text,
    notes_exit text
);

create index if not exists idx_journal_trade_close_events_trade_id on public.journal_trade_close_events (trade_id);
create index if not exists idx_journal_trade_close_events_event_datetime on public.journal_trade_close_events (event_datetime asc);

create table if not exists public.active_trades (
    trade_id bigint primary key references public.journal_trades(id) on delete cascade,
    system_name text not null,
    trade_mode text not null check (trade_mode in ('real', 'simulated')),
    current_management_status text,
    previous_management_status text,
    current_thesis_status text,
    previous_thesis_status text,
    concise_reason text,
    reason_code text,
    next_trigger text,
    trigger_source text,
    last_evaluated_at timestamptz,
    last_alert_sent_at timestamptz,
    last_alert_type text,
    last_alert_priority integer,
    alert_count integer not null default 0,
    last_alert_reason_code text,
    last_underlying_price double precision,
    last_distance_to_short double precision,
    last_distance_to_long double precision,
    last_buffer_remaining_percent double precision
);

create table if not exists public.active_trade_alert_log (
    id bigint generated by default as identity primary key,
    trade_id bigint not null references public.journal_trades(id) on delete cascade,
    system_name text not null,
    trade_mode text not null check (trade_mode in ('real', 'simulated')),
    alert_type text not null,
    alert_priority integer not null,
    alert_priority_label text not null,
    reason_code text,
    title text not null,
    body text not null,
    sent_at timestamptz not null
);

create table if not exists public.management_runtime_settings (
    singleton_id integer primary key,
    notifications_enabled boolean not null default true,
    last_morning_snapshot_date text,
    last_eod_summary_date text,
    last_background_run_at timestamptz,
    constraint management_runtime_settings_singleton_check check (singleton_id = 1)
);

insert into public.management_runtime_settings (singleton_id, notifications_enabled)
values (1, true)
on conflict (singleton_id) do nothing;

create table if not exists public.performance_metrics (
    id bigint generated by default as identity primary key,
    trade_mode text not null check (trade_mode in ('real', 'simulated')),
    metric_scope text not null,
    metric_key text not null,
    metric_value_numeric double precision,
    metric_value_text text,
    updated_at timestamptz not null default now(),
    constraint performance_metrics_unique_metric unique (trade_mode, metric_scope, metric_key)
);

create index if not exists idx_active_trades_trade_mode on public.active_trades (trade_mode);
create index if not exists idx_active_trade_alert_log_trade_id on public.active_trade_alert_log (trade_id);
create index if not exists idx_performance_metrics_trade_mode on public.performance_metrics (trade_mode);